# Dependencies
markdown:         redcarpet
highlighter:      rouge
gems: [jekyll-gist,rouge]

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            LT
tagline:          'Мысли от Лариона'
description:      'Блог Турло Лариона'
url:              http://lt-web.ru
baseurl:          /

author:
  name:           'Ларион Турло'
  url:            https://github.com/larionturlo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/larionturlo